
import java.awt.Color;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CHOICE.java
 *
 * Created on Dec 22, 2013, 10:57:56 PM
 */

/**
 *
 * @author ATULE
 */
public class CHOICE extends javax.swing.JFrame {

    /** Creates new form CHOICE */
    public CHOICE() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        rb2 = new javax.swing.JRadioButton();
        rb1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rb2.setFont(new java.awt.Font("Bogusflow", 3, 48));
        rb2.setForeground(new java.awt.Color(51, 51, 255));
        rb2.setText("GROOM");
        rb2.setOpaque(false);
        rb2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rb2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rb2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rb2MousePressed(evt);
            }
        });
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });
        jPanel2.add(rb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 260, 70));

        rb1.setFont(new java.awt.Font("Bogusflow", 3, 48));
        rb1.setForeground(new java.awt.Color(51, 51, 255));
        rb1.setText("BRIDE");
        rb1.setOpaque(false);
        rb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rb1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rb1MouseExited(evt);
            }
        });
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });
        jPanel2.add(rb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 260, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 590));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ff04b.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        // TODO add your handling code here:

         if (rb1.isSelected())
        {    SHOPPING SH=new SHOPPING();
        SH.setVisible(true);
        this.setVisible(false);
        }
}//GEN-LAST:event_rb1ActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
        // TODO add your handling code here:
         if (rb2.isSelected())
        {    GRSHOPPING GSH=new GRSHOPPING();
        GSH.setVisible(true);
        this.setVisible(false);
        }
    }//GEN-LAST:event_rb2ActionPerformed

    private void rb1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb1MouseEntered
        // TODO add your handling code here:
        rb1.setForeground(Color.red);
    }//GEN-LAST:event_rb1MouseEntered

    private void rb1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb1MouseExited
        // TODO add your handling code here:
        rb1.setForeground(Color.blue);
    }//GEN-LAST:event_rb1MouseExited

    private void rb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb1MouseClicked
        // TODO add your handling code here:
        rb1.setForeground(Color.green);
    }//GEN-LAST:event_rb1MouseClicked

    private void rb2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb2MouseEntered
        // TODO add your handling code here:
         rb2.setForeground(Color.red);

    }//GEN-LAST:event_rb2MouseEntered

    private void rb2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb2MousePressed
        // TODO add your handling code here:
         rb2.setForeground(Color.green);
    }//GEN-LAST:event_rb2MousePressed

    private void rb2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb2MouseExited
        // TODO add your handling code here:
         rb2.setForeground(Color.blue);
    }//GEN-LAST:event_rb2MouseExited

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CHOICE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    // End of variables declaration//GEN-END:variables

}
