
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SHOPPING.java
 *
 * Created on Dec 22, 2013, 10:13:14 PM
 */

/**
 *
 * @author ATULE
 */
public class SHOPPING extends javax.swing.JFrame {

    /** Creates new form SHOPPING */
    public SHOPPING() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cb2 = new javax.swing.JComboBox();
        l1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cb3 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        te = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        t6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(102, 255, 102));

        jLabel1.setFont(new java.awt.Font("BlackCastleMF", 3, 48));
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("BIG  BAZAAR");

        jLabel2.setFont(new java.awt.Font("Budmo Jiggler", 3, 24));
        jLabel2.setForeground(new java.awt.Color(102, 255, 102));
        jLabel2.setText("DRESSES");

        cb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT", "LEHNGA-1", "LEHNGA-2", "LEHNGA-3", "LEHNGA-4", "SALWAR SUIT-1", "SALWAR SUIT-2", "SALWAR SUIT-3", "SAREE", "WESTERN GAOWN-1", "WESTERN GAOWN-2", " ", " " }));
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Budmo Jiggler", 3, 24));
        jLabel3.setForeground(new java.awt.Color(102, 255, 102));
        jLabel3.setText("JEWELLERY");

        cb2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT", "NECKLACE-1", "NECKLACE-2", "NECKLACE-3", "NECKLACE-4", "BANGLES-1", "BANGLES-2", "BANGLES-3", "BANGLES-4", "GOLD BANGLES", "PAYAL", "DIAMOND EARINGS-1", "DIAMOND EARINGS-2", "GOLD EARINGS-1", "GOLD EARINGS-2", "RING", "BRACELET-1", "BRACELET-2", " " }));
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });

        l1.setBackground(new java.awt.Color(0, 0, 0));
        l1.setOpaque(true);

        jLabel5.setFont(new java.awt.Font("Budmo Jiggler", 3, 24));
        jLabel5.setForeground(new java.awt.Color(102, 255, 102));
        jLabel5.setText("FOOT WEARS");

        cb3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT", "FLAT-1", "FLAT-2", "FLAT-3 ", "HEELS-1", "HEELS-2", "HEELS-3", "BELLY-1", "BELLY-2", "BELLY-3", " " }));
        cb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb3ActionPerformed(evt);
            }
        });

        jButton1.setText("NEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("INSERT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "DRESS", "JEWELLERY", "FOOTWEARS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb);

        jButton3.setText("SHOW");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Budmo Jiggler", 3, 24));
        jLabel4.setForeground(new java.awt.Color(102, 255, 102));
        jLabel4.setText("NAME");

        te.setBackground(new java.awt.Color(255, 204, 204));
        te.setFont(new java.awt.Font("Tahoma", 0, 18));

        jButton5.setText("BUY DRESS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("BUY JEWELLERY");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("BUY FOOTWEARS");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(92, 92, 92)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cb3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(112, 112, 112)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jButton5)
                                                        .addGap(33, 33, 33)
                                                        .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jButton6)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(t3))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jButton7)
                                                        .addGap(31, 31, 31)
                                                        .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(79, 79, 79)
                                                .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(144, 144, 144)
                                        .addComponent(jButton2)
                                        .addGap(94, 94, 94)
                                        .addComponent(jButton3)
                                        .addGap(31, 31, 31)
                                        .addComponent(te, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(405, 405, 405)
                .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(407, 407, 407))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(479, 479, 479)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1160, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t1)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(te, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6)
                            .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7)
                            .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)))
                .addGap(3, 3, 3)
                .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(526, 526, 526))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
        int n=cb1.getSelectedIndex();
        int amt;
        switch(n)
        {  case 1:     l1.setIcon(new ImageIcon("src//l1.jpg"));
                     amt= 1599; te.setText(""+amt);
                         break;
                          case 2:     l1.setIcon(new ImageIcon("src//l2.jpg"));
                                       amt= 5999; te.setText(""+amt);
                         break;
                          case 3:     l1.setIcon(new ImageIcon("src//l3.jpg"));
                                        amt= 7999; te.setText(""+amt);

                         break;
                          case 4:     l1.setIcon(new ImageIcon("src//l4.jpg"));
                                      amt= 10000; te.setText(""+amt);

                         break;
                          case 5:     l1.setIcon(new ImageIcon("src//ss1.jpg"));
                                       amt= 1999; te.setText(""+amt);

                         break;
                          case 6:     l1.setIcon(new ImageIcon("src//ss2.jpg"));
                                   amt= 3999; te.setText(""+amt);

                         break;
                          case 7:     l1.setIcon(new ImageIcon("src//ss3.jpg"));
                                    amt= 2999; te.setText(""+amt);

                         break;
                         
                          case 8:     l1.setIcon(new ImageIcon("src//s1.jpg"));
                                     amt= 4999; te.setText(""+amt);

                         break;
                         case 9:     l1.setIcon(new ImageIcon("src//g1.jpg"));
                                    amt= 9999; te.setText(""+amt);

                         break;
                         case 10:     l1.setIcon(new ImageIcon("src//g2.jpg"));
                                        amt= 8999; te.setText(""+amt);

                         break;

        }



}//GEN-LAST:event_cb1ActionPerformed

        private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed
            // TODO add your handling code here:
              int n1=cb2.getSelectedIndex();
int amt;
        switch(n1)
        {  case 1:     l1.setIcon(new ImageIcon("src//n1.jpg"));
                        amt= 180000; te.setText(""+amt);
                       break;

           case 2:     l1.setIcon(new ImageIcon("src//n2.jpg"));
                        amt= 200000; te.setText(""+amt);
                        break;
             case 3:     l1.setIcon(new ImageIcon("src//n3.jpg"));
                         amt= 400000; te.setText(""+amt);

                        break;
                          case 4:     l1.setIcon(new ImageIcon("src//n4.jpg"));
                                  amt= 300000; te.setText(""+amt);

                                       break;
                           case 5:     l1.setIcon(new ImageIcon("src//b1.jpg"));
                                   amt= 1000; te.setText(""+amt);

                                        break;

                         case 6:     l1.setIcon(new ImageIcon("src//b2.jpg"));
                                   amt= 999; te.setText(""+amt);

                                       break;

                         case 7 :     l1.setIcon(new ImageIcon("src//b3.jpg"));
                                        amt= 1999; te.setText(""+amt);

                                       break;
                         case 8:     l1.setIcon(new ImageIcon("src//b4.jpg"));
                                        amt= 1100; te.setText(""+amt);

                                       break;
                         case 9:     l1.setIcon(new ImageIcon("src//ge1.jpg"));
                                    amt= 50000; te.setText(""+amt);

                                      break;

                          case 10:     l1.setIcon(new ImageIcon("src//p1.jpg"));
                                      amt= 2299; te.setText(""+amt);

                        break;
                         case 11:     l1.setIcon(new ImageIcon("src//de1.jpg"));
                                     amt= 100000; te.setText(""+amt);

                        break;
                         case 12:     l1.setIcon(new ImageIcon("src//de2.jpg"));
                                    amt= 150000; te.setText(""+amt);

                        break;
                         case 13:     l1.setIcon(new ImageIcon("src//ge2.jpg"));
                                amt= 30000; te.setText(""+amt);

                        break;
                         case 14:     l1.setIcon(new ImageIcon("src//ge3.jpg"));
                                      amt= 25000; te.setText(""+amt);

                        break;
                         case 15:     l1.setIcon(new ImageIcon("src//r1.jpg"));
                                     amt= 100000; te.setText(""+amt);

                        break;
                         case 16:     l1.setIcon(new ImageIcon("src//br.jpg"));
                                      amt= 180000; te.setText(""+amt);

                                    break;
                                  case 17:     l1.setIcon(new ImageIcon("src//br1.jpg"));
                                                amt= 10000; te.setText(""+amt);

                        break;


        }

        }//GEN-LAST:event_cb2ActionPerformed

        private void cb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb3ActionPerformed
            // TODO add your handling code here:

             int n2=cb3.getSelectedIndex();
int amt;
        switch(n2)
        {  case 1:     l1.setIcon(new ImageIcon("src//f1.jpg"));
                         amt= 599; te.setText(""+amt);
                       break;

           case 2:     l1.setIcon(new ImageIcon("src//f2.jpg"));
                         amt= 399; te.setText(""+amt);
                        break;
             case 3:     l1.setIcon(new ImageIcon("src//f3.jpg"));
                         amt= 899; te.setText(""+amt);

                        break;
                          case 4:     l1.setIcon(new ImageIcon("src//h1.jpg"));
                                      amt= 999; te.setText(""+amt);

                                       break;
                           case 5:     l1.setIcon(new ImageIcon("src//h2.jpg"));
                                        amt= 950; te.setText(""+amt);

                                        break;

                         case 6:     l1.setIcon(new ImageIcon("src//h3.jpg"));
                                     amt= 850; te.setText(""+amt);

                                       break;

                         case 7 :     l1.setIcon(new ImageIcon("src//bb1.jpg"));
                                    amt= 699; te.setText(""+amt);

                                       break;
                         case 8:     l1.setIcon(new ImageIcon("src//bb2.jpg"));
                                    amt= 899; te.setText(""+amt);

                                       break;
                         case 9:     l1.setIcon(new ImageIcon("src//bb3.jpg"));
                                      amt= 499; te.setText(""+amt);

                                      break;
        }

        }//GEN-LAST:event_cb3ActionPerformed

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            // TODO add your handling code here

            
          
        String name=t1.getText();
        int d=Integer.parseInt(t4.getText());
         int jew=Integer.parseInt(t3.getText());
          int fo=Integer.parseInt(t2.getText());

        try
        { Class.forName("java.sql.DriverManager");
          Connection con1=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/school","root","mps");
          Statement stmt=(Statement) con1.createStatement();
          String query="INSERT INTO shop(NAME,DRESS,JEWELLERY,FOOTWEARS) VALUES ( ' "+name+" ',' "+d+" '  ,' "+jew+" ' , ' "+fo+" ');";
          stmt.executeUpdate(query);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
           
           
          
            

        }//GEN-LAST:event_jButton2ActionPerformed

        private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            // TODO add your handling code here:

             DefaultTableModel model = (DefaultTableModel)tb.getModel();

        try
        { Class.forName("java.sql.DriverManager");
          Connection con1=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/school","root","mps");
          Statement stmt=(Statement)con1.createStatement();

          String query="SELECT * FROM shop;";

          ResultSet rs=stmt.executeQuery(query);
          while (rs.next())
          {  String name=rs.getString("NAME");
             int d=rs.getInt("DRESS");
             int jew=rs.getInt("JEWELLERY");
             int fo=rs.getInt("FOOTWEARS");
            
            model.addRow (new Object[] { name,d,jew,fo});



          }
          rs.close();
          stmt.close();
          con1.close();
          }
        catch(Exception e)
        { JOptionPane.showMessageDialog(null, e.getMessage());
    }
        }//GEN-LAST:event_jButton3ActionPerformed

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            // TODO add your handling code here:

             UPDATE U=new UPDATE ();
        U.setVisible(true);
        this.setVisible(false);
        }//GEN-LAST:event_jButton1ActionPerformed

        private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            // TODO add your handling code here:



            int am=Integer.parseInt(te.getText());

            
            t4.setText(""+(am));

            
            
        }//GEN-LAST:event_jButton5ActionPerformed

        private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
            // TODO add your handling code here:
             int am=Integer.parseInt(te.getText());

          
            t3.setText(""+(am));




        }//GEN-LAST:event_jButton6ActionPerformed

        private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
            // TODO add your handling code here:
             int am=Integer.parseInt(te.getText());


            t6.setText(""+(am));
        }//GEN-LAST:event_jButton7ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SHOPPING().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb1;
    private javax.swing.JComboBox cb2;
    private javax.swing.JComboBox cb3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t6;
    private javax.swing.JTable tb;
    private javax.swing.JTextField te;
    // End of variables declaration//GEN-END:variables

}
